openapi: "3.0.0"
info:
  title: "Piattaforma Contenuti Musicali"
  version: "1.0"
  description: Documentazione che descrive l'utilizzo delle API messe a disposizione dalla Piattaforma Contenuti Musicali, fruibile tramite l'utilizzo del bot di Telegram @FindYourFavouriteMusicBot. Per maggiori informazioni, usufruire della repository dedicata su GitHub contenente la descrizione della struttura della piattaforma ed una specifica maggiormente dettagliata.<br><br><a href="https://github.com/m-dilorenzi/piattaformaContenutiMusicali.git">Repository GitHub</a>

servers:
  - url: "https://piattaformacontenutimusicali.herokuapp.com"

tags:
- name: help
  description: Mostra all'utente tutte le funzioni disponibili.
- name: iTunes
  description: Permette all'utente di ricercare un brano o una pagina di un artista all'interno dell'iTunes Store. 
- name: YouTube
  description: Permette all'utente di ricercare video musicali su YouTube.
- name: Spotify
  description: Permette all'utente di ricercare un brano su Spotify. 

paths:
  /help:
    get:
      tags:
      - help
      summary: Mostra le funzioni disponibili
      description: Visualizza all'utente le funzionalità fornite dall'API
      
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    example: Benvenuto nel bot FindYourFavouriteMusic!\nI possibili comandi sono:\n1. /searchsongbyparameter\n  Permette di ricercare una canzone o una lista di canzoni tramite parametri come nome della canzone, artista, album, ecc.ecc. La ricerca puo' essere eseguita anche tramite un insieme di termini.\n2. /getartistpagebyname\n  Permette di ricercare la pagina iTunes di un cantante (o le pagine nel caso in cui i risultati della ricerca siano piu' di uno) alla quale si potra' poi accedere successivamente tramite l'apposito link che verra' mostrato.\n3. /searchyoutubevideos\n  Mostra i primi 5 video su YouTube che soddisfano i requisiti specificati nella ricerca.\n4. /searchsongonspotify\n  Mostra al piu' 5 canzoni con il rispettivo link di Spotify che soddisfano i requisiti specificati nella ricerca dall'utente.
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 400
                  message: Bad Request
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 500
                  message: Try later
        
        
      
  /searchiTunesSong/{terminiDiRicerca}:
    get:
      tags:
        - iTunes
      summary: Permette la ricerca su iTunes di un brano 
      description: Specificati i termini di ricerca, quali titolo del brano, l'album di appartenenza o l'autore, questa funzione permette di ricercare all'interno dell'iTunes Store un brano.
      parameters:
        - in: path
          name: terminiDiRicerca
          description: Termini utilizzati per la ricerca del brano. Più termini verranno specificati, più preciso sarà il risultato.
          required: true
          schema:
            type: string
            default: prova
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  tipoRisultato: 
                    type: string
                    example: iTunesSong
                  risultatiTotali: 
                    type: integer
                    example: 1
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        nome:
                          type: string
                          example: Ciao
                        album:
                          type: string
                          example: Faccio un casino
                        autore:
                          type: string
                          example: Coez
                        prezzo:
                          type: number
                          example: 0.99
                        link:
                          type: string
                          example: https://music.apple.com/us/album/ciao/1324328640?i=1324328644&uo=4
                        
                        
                        
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 400
                  message: Bad Request
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 500
                  message: Try later
  
  /searchiTunesArtist/{terminiDiRicerca}:
    get:
      tags:
        - iTunes
      summary: Permette la ricerca su iTunes di un artista 
      description: Specificato il termine di ricerca, ovvero il nome dell'artista da ricercare, questa funzione permette di ricercare all'interno dell'iTunes Store un artista.
      parameters:
        - in: path
          name: terminiDiRicerca
          description: Termini utilizzati per la ricerca dell'artista.
          required: true
          schema:
            type: string
            default: prova
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  tipoRisultato: 
                    type: string
                    example: iTunesArtist
                  risultatiTotali: 
                    type: integer
                    example: 1
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        nome:
                          type: string
                          example: Vasco Rossi
                        album:
                          type: string
                          example: 0
                        autore:
                          type: string
                          example: 0
                        prezzo:
                          type: number
                          example: 0
                        link:
                          type: string
                          example: https://music.apple.com/us/artist/vasco-rossi/14589739?uo=4
                          
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 400
                  message: Bad Request
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 500
                  message: Try later
                  
  /searchYoutubeVideos/{terminiDiRicerca}:
    get:
      tags:
        - YouTube
      summary: Permette la ricerca di video su YouTube 
      description: Specificato il termine di ricerca, ovvero il titolo della canzone, o l'artista, questa funzione permette di ricercare all'interno di YouTube dei video musicali.
      parameters:
        - in: path
          name: terminiDiRicerca
          description: Termini utilizzati per la ricerca del video.
          required: true
          schema:
            type: string
            default: prova
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  tipoRisultato: 
                    type: string
                    example: YouTubeVideo
                  risultatiTotali: 
                    type: integer
                    example: 3
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        nome:
                          type: string
                          
                        album:
                          type: string
                          
                        autore:
                          type: string
                          
                        prezzo:
                          type: number
                          
                        link:
                          type: string
                    
                    example:
                      - nome: Coez - Ciao
                        album: 0
                        autore: 0
                        prezzo: 0
                        link: www.youtube.com/watch?v=0GO0YdJvy_s
                      - nome: Coez - Ciao
                        album: 0
                        autore: 0
                        prezzo: 0
                        link: www.youtube.com/watch?v=xdGGkDkkCS0
                      - nome: Coez - Ciao (live)
                        album: 0
                        autore: 0
                        prezzo: 0
                        link: www.youtube.com/watch?v=hC01zbJRT9w
                                
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 400
                  message: Bad Request
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 500
                  message: Try later
  
  /searchSongOnSpotify/{terminiDiRicerca}/{token}:
    get:
      tags:
        - Spotify
      summary: Permette la ricerca di un brano su Spotify 
      description: Specificato il termine di ricerca, ovvero il titolo della canzone, o l'artista, ed un token valido, questa funzione permette di ricercare all'interno di Spotify un brano.
      parameters:
        - in: path
          name: terminiDiRicerca
          description: Termini utilizzati per la ricerca del video.
          required: true
          schema:
            type: string
            default: prova
        - in: path
          name: token
          description: Token temporaneo utilizzato per effettuare la ricerca su Spotify
          required: true
          schema:
            type: string
            default: token
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  tipoRisultato: 
                    type: string
                    example: SpotifySong
                  risultatiTotali: 
                    type: integer
                    example: 1
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        nome:
                          type: string
                          
                        album:
                          type: string
                          
                        autore:
                          type: string
                          
                        prezzo:
                          type: number
                          
                        link:
                          type: string
                    
                    example:
                      - nome: Ciao
                        album: 0
                        autore: Coez
                        prezzo: 0
                        link: https://open.spotify.com/track/3OME70nD4TS08u5XBBK44d
                         
                                
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 400
                  message: Bad Request
                  
        '401':
          description: token expired
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 401
                  message: token expired
        
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                  message: 
                    type: string
                example:
                  result: 500
                  message: Try later